"""Hand-authored fictional demo referrals, independent of generated CSV templates."""

EXAMPLES = {
    "ICU support + capacity constraint": "SYNTHETIC CASE. 67-year-old adult. Presenting problem: septic shock. Requested service: critical care. Requested bed: ICU. Currently on nasal cannula. Currently on norepinephrine. SBP 86 mmHg. HR 118 bpm. SpO2 94%. Continuous cardiac monitoring required. No specialty evaluation required. Isolation: contact. Consultants: critical care. Referring facility: Synthetic North Hospital. Urgency: emergent. Bed availability: unavailable.",
    "Telemetry referral": "SYNTHETIC CASE. Age: 58. Presenting problem: atrial fibrillation. Service: cardiology. Requested bed: telemetry. Currently on room air. No vasopressors. HR 108 bpm. SBP 122 mmHg. SpO2 97%. Telemetry required. No specialty evaluation required. Isolation: none. Consultants: cardiology. Referring facility: Synthetic Valley ED. Urgency: urgent. Bed availability: available.",
    "Medical/surgical referral": "SYNTHETIC CASE. 45-year-old adult. Presenting problem: cellulitis. Service: internal medicine. Requested bed: medical/surgical. Currently on room air. No vasopressors. SBP 124 mmHg. HR 82 bpm. SpO2 98%. No cardiac monitoring needed. No specialty evaluation required. Isolation: none. Consultants: internal medicine. Referring facility: Synthetic Prairie Hospital. Urgency: routine. Bed availability: available.",
    "Specialty acceptance needed": "SYNTHETIC CASE. Age: 39. Presenting problem: transplant complication. Service: transplant. Requested bed: specialty review. Currently on room air. No vasopressors. SBP 128 mmHg. HR 88 bpm. SpO2 98%. No cardiac monitoring needed. Specialty evaluation required. Isolation: none. Consultants: transplant. Referring facility: Synthetic Lakeside Center. Urgency: urgent. Bed availability: limited.",
    "Incomplete referral": "SYNTHETIC CASE. Age: 72. Presenting problem: pneumonia. Service: internal medicine. Requested bed: medical/surgical. Oxygen support: unknown. Referring facility: Synthetic West Community. Urgency: urgent.",
    "Conflicting pressor documentation": "SYNTHETIC CASE. 64-year-old adult. Presenting problem: hypotension. Service: internal medicine. Currently on room air. No vasopressors. Currently on norepinephrine. Telemetry required. No specialty evaluation required. SBP 94 mmHg. HR 105 bpm. SpO2 96%. Isolation: none.",
}
